; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = 
	kkloesener/MFRC522_I2C@^1.0
	bblanchon/ArduinoJson@^7.2.2

[env:esp32-s3]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_flags =
    ;-DARDUINO_USB_CDC_ON_BOOT=1
	-DOLED_SSD1315_ENABLE=1  ; Active la bibliothèque SSD1315
  	-DOLED_PLATFORM_ARDUINO=1  ; Active le flag pour Arduino pour la bibliothèque SSD1315
monitor_port = COM10
monitor_speed = 115200
monitor_filters = esp32_exception_decoder  ; ← décode le backtrace automatiquement
build_type = debug                          ; ← garde les symboles de debug
;upload_port = COM9
upload_protocol = esptool
lib_deps = 
	links2004/WebSockets@^2.4.1
	knolleary/PubSubClient@^2.8
	kkloesener/MFRC522_I2C@^1.0
	bblanchon/ArduinoJson@^7.2.2
	boriasrazor/oled_ssd1315@^3.0.1
